perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_homogeneity.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_arbit_banach_space_norm.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_custom_func1.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_hlf.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_group_homomorphism.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_hlf_extended.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_slf.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_banach_space.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_group.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_arbit_custom_func2.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_qhf.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_arbit_group_id.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_arbit_banach_space_set.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_arbit_qhf.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_arbit_plf.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_custom_func2.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_length_function.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_plf.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_arbit_banach_space.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_hplf.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_arbit_group_set.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_arbit_homomorphism.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_arbit_group_op.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./terms/T_arbit_group.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./projects/J.zMa.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./projects/J.zDY.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./projects/J.Ro4.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./projects/J_polymath14.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_p4.3.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_t4.6.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_e2.6.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_p2.1.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_r2.9.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_project_main.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_6.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_t1.2.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_2.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_5.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_cauchy.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_r2.5.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_r3.1.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_c2.12.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_p4.1.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_e2.7.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_l2.8.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_conj_inv.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_1.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_4.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_l2.10.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_c1.4.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_t4.4.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./propositions/P_main_3.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./commonResource.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg3.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg8.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg16.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg13.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg6.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg15.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg12.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg14.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg1.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg7.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg4.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg9.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg5.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg22.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg11.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg10.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./arguments/A_arg2.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./articles/R.8yN.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./articles/R.Ro4.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./commonPage.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./beliefsets/B.Ro4.json &
perl -i -p0e 's/\"contributor\": \{\n    \"handle\"\: \"abc\"\n  \},\n  //' ./beliefsets/B.default.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/zDY:pages/J.zDY:element-norm-bounds.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/zDY:pages/J.zDY:proof-discovery-tree.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/zDY:pages/J.zDY:constructions.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:solved.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:feedback.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:conclusion.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:questions.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:constructions.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:element-norm-bounds.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:updates.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:subgroups.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:inward-repetition.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:writing.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:proof-discovery-tree.json &
perl -i -p0e 's/,\n  \"contributor\": \{\n    \"handle\"\: \"abc\"\n  \}//' ./projects/polymath14:pages/J_polymath14:automation.json